import { useMemo } from "react";

export function useEvidenceReport(evidencePack, sessions, risks, summary) {
  const report = useMemo(() => {
    const completedSessions = sessions.filter((s) => s.status === "completed");

    return `# BobTrace Evidence Pack
## ${evidencePack.projectName}

**Generated:** ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}  
**IBM Bob Version:** ${evidencePack.bobVersion}  
**Total Sessions:** ${evidencePack.totalSessions}  
**Files Modified:** ${evidencePack.totalFilesModified}  
**Tokens Used:** ${evidencePack.totalTokensUsed.toLocaleString()}

---

## Executive Summary

BobTrace demonstrates how IBM Bob accelerates software delivery while maintaining enterprise compliance standards. This evidence pack documents all AI-assisted development sessions, decisions made, risks identified, and human oversight applied.

**Key Achievements:**
- ${completedSessions.length} development phases completed with IBM Bob assistance
- ${summary.filesChanged} files modified with full audit trail
- ${summary.testsGenerated} tests generated for quality assurance
- ${summary.risksDetected} risks identified and mitigated
- Evidence readiness score: ${summary.evidenceReadiness}%

---

## IBM Bob Usage Summary

IBM Bob was used across ${sessions.length} distinct development phases:

${sessions
  .map(
    (session) => `### ${session.phase}: ${session.name}
**Date:** ${session.date}  
**Status:** ${session.status}  
**Purpose:** ${session.purpose}

**Key Decisions:**
${session.keyDecisions.map((d) => `- ${d}`).join("\n")}

**Files Affected:** ${session.filesAffected.length > 0 ? session.filesAffected.join(", ") : "None"}  
**Evidence Location:** \`${session.evidenceSaved}\`

`,
  )
  .join("\n")}

---

## Session Timeline

All IBM Bob sessions are documented with:
- Exported task history markdown files
- Token consumption screenshots
- Session notes and decisions
- Files modified during each session

**Evidence Storage:** All session artifacts stored in \`bob_sessions/\` directory with phase-based organization.

---

## Risk Assessment

${risks
  .map(
    (risk) => `### ${risk.title}
**Severity:** ${risk.severity.toUpperCase()}  
**Status:** ${risk.status}  
**Description:** ${risk.description}  
**Mitigation:** ${risk.mitigation}

`,
  )
  .join("\n")}

---

## Quality Assurance

**Tests Generated:** ${summary.testsGenerated}  
**Testing Approach:** Manual validation for MVP, automated tests planned for production

**Test Coverage:**
- Component rendering validation
- User interaction flows
- Evidence export functionality
- Responsive design verification

---

## Human Review Checklist

Before deployment, the following human reviews are REQUIRED:

- [ ] Code review by senior engineer
- [ ] Security audit completed
- [ ] No credentials or secrets in code
- [ ] All AI-generated code validated
- [ ] Business logic verified
- [ ] User experience tested
- [ ] Documentation reviewed
- [ ] Compliance requirements met
- [ ] Performance benchmarks met
- [ ] Accessibility standards verified

---

## Compliance Notes

This project was developed for the IBM Bob Dev Day Hackathon. All AI-assisted development sessions are fully documented with:

1. **Session Evidence:** Task history exports and consumption data
2. **Decision Tracking:** Key architectural and implementation decisions
3. **Risk Management:** Identified risks with mitigation strategies
4. **Human Oversight:** Required review checkpoints documented

**Audit Trail:** Complete session history available in \`bob_sessions/\` directory.

---

## Conclusion

BobTrace demonstrates that AI-assisted development can meet enterprise compliance standards when proper evidence collection and human oversight processes are in place. This evidence pack provides full transparency into the development process, enabling confident deployment decisions.

**Next Steps:**
1. Complete human code review
2. Perform security audit
3. Execute full test suite
4. Obtain deployment approval
5. Deploy to production environment

---

*Generated by BobTrace - From AI Coding to Auditable Delivery*
`;
  }, [evidencePack, sessions, risks, summary]);

  return report;
}

// Made with Bob
